version: "3.0"
services:
  backend: # 컨테이너
    image: pll0123/backend
    ports:
      - '8080:8080'
    env_file:
      - ./.env/app.env
    container_name: "backend"
    depends_on:
      - database
    networks:
      - app-network
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == worker ]

  database:
    image: "postgres:16.2-alpine3.19"
    ports:
      - '5432:5432'
    env_file:
      - ./.env/app.env
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == worker ]

networks:
  app-network:
    external: true