version: "3.0"
services:
  backend: # 컨테이너
    build: .
    ports:
      - '8080:8080'
    env_file:
      - ./.env/app.env
    container_name: "backend"
    depends_on:
      - database

  database:
    image: "postgres:16.2-alpine3.19"
    ports:
      - '5432:5432'
    env_file:
      - ./.env/app.env
