spring:
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_USER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
