name: hello-github-actions!
on: [push]

jobs:
  build-and-push:
    runs-on:
      - self-hosted

    steps:
      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '21'

