name: hello-github-actions!
on: [push]

jobs:
  build-and-push:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: gradle bootjar
          # 처음에 ./gradlew 파일을 실행할 수 없어서, chmod 로 실행 가능하도록 바꿔줍니다
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: docker build
        run: |
          docker build -t pll0123/backend:latest .

      - name: Login docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Push Docker image to Docker Hub
        run: docker push pll0123/backend:latest

      - name: Deploy to EC2 with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECC_IP }}
          username: ubuntu
          key: ${{ secrets.ECC_PEM }}
          script: |
            cd ~/
            scp -o StrictHostKeyChecking=no -i ${{ secrets.ECC_PEM }} ./docker-compose.yml ubuntu@${{ secrets.ECC_IP }}:~/
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.ECC_PEM }} ubuntu@${{ secrets.ECC_IP }} 'docker-compose -f /home/ubuntu/docker-compose.yml pull && docker-compose -f /home/ubuntu/docker-compose.yml up -d'